"""add_chat_type_and_status_to_chat_messages

Revision ID: 70e296cc56e9
Revises: dc2331b01ddd
Create Date: 2025-11-18 10:37:21.792766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e296cc56e9'
down_revision: Union[str, None] = 'dc2331b01ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('chat_type', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'status')
    op.drop_column('chat_messages', 'chat_type')
    # ### end Alembic commands ###

