#!/usr/bin/env python3
"""
Script untuk menganalisis mapping field account_name, account_id, user_id, profile_picture_url
dari berbagai tool (Oxygen, Cellebrite, Axiom) dan dokumentasi mapping yang benar
"""

import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

print("=" * 100)
print("ANALISIS MAPPING FIELD SOCIAL MEDIA DARI BERBAGAI TOOL")
print("=" * 100)
print()

print("📋 DOKUMENTASI MAPPING FIELD:")
print("-" * 100)
print()

# Mapping untuk Oxygen
print("🔵 OXYGEN FORENSICS:")
print()
print("  1. Instagram Sheets:")
print("     - Users-Following sheet:")
print("       • account_name = 'User name' column")
print("       • account_id = 'User ID' column")
print("       • user_id = 'User ID' column (sama dengan account_id)")
print("       • profile_picture_url = 'User picture URL' column")
print()
print("     - Users-Followers sheet:")
print("       • account_name = 'User name' column")
print("       • account_id = 'UID' column")
print("       • user_id = 'UID' column (sama dengan account_id)")
print("       • profile_picture_url = 'User picture URL' column")
print()
print("  2. X/Twitter Sheets:")
print("     - Users-Followers sheet:")
print("       • account_name = 'User name' column")
print("       • account_id = 'UID' column")
print("       • user_id = 'UID' column (sama dengan account_id)")
print("       • profile_picture_url = 'User picture URL' column")
print()
print("     - Tweets-Following / Tweets-Other:")
print("       • account_name = 'User name' column")
print("       • account_id = 'User ID' column")
print("       • user_id = 'User ID' column (sama dengan account_id)")
print("       • profile_picture_url = None (tidak ada di sheet ini)")
print()
print("  3. Contacts Sheet (untuk semua platform):")
print("     - account_name = Extract dari 'Contact' field (first line atau setelah 'Instagram ID:', dll)")
print("     - account_id = Extract dari 'Internet' field menggunakan pattern regex:")
print("       • Instagram: r'Instagram ID:\\s*(\\S+)'")
print("       • Facebook: r'Facebook ID:\\s*(\\S+)'")
print("       • Telegram: r'Telegram ID:\\s*(\\S+)'")
print("       • X/Twitter: r'Account name:\\s*(\\S+)'")
print("       • WhatsApp: r'(WhatsApp|Phone)\\s*(ID|number):\\s*([+\\d\\s\\-\\(\\)]+)'")
print("     - user_id = Extract dari 'Internet' atau 'Phones & Emails' field:")
print("       • Instagram: r'instagram\\s+id[:\\s]*(\\d+)'")
print("       • X/Twitter: r'x\\s+id[:\\s]*(\\d+)' atau r'twitter\\s+id[:\\s]*(\\d+)'")
print("       • Telegram: r'telegram\\s+id[:\\s]*(\\d+)'")
print("     - profile_picture_url = Extract dari 'Internet' field:")
print("       • Pattern: r'https?://[^\\s]+\\.(?:jpg|jpeg|png|gif)'")
print()

# Mapping untuk Magnet Axiom
print()
print("🔴 MAGNET AXIOM:")
print()
print("  1. Instagram Profiles sheet:")
print("     • account_name = 'User Name' column")
print("     • account_id = 'User Name' column (username sebagai account_id)")
print("     • user_id = 'User ID' column (numeric ID)")
print("     • profile_picture_url = 'Profile Picture URL' column")
print()
print("  2. Android Instagram Following sheet:")
print("     • account_name = 'User Name' column")
print("     • account_id = 'User Name' column")
print("     • user_id = 'ID' column")
print("     • profile_picture_url = 'Profile Picture URL' column")
print()
print("  3. Android Instagram Users sheet:")
print("     • account_name = 'User Name' column")
print("     • account_id = 'User Name' column")
print("     • user_id = 'ID' column")
print("     • profile_picture_url = None (tidak ada di sheet ini)")
print()
print("  4. Twitter Users sheet:")
print("     • account_name = 'Screen Name' column")
print("     • account_id = 'Screen Name' column")
print("     • user_id = 'User ID' column")
print("     • profile_picture_url = 'Profile Picture URL' column")
print()
print("  5. Telegram Accounts sheet:")
print("     • account_name = 'Username' column")
print("     • account_id = 'Account ID' column")
print("     • user_id = 'User ID' column")
print("     • profile_picture_url = 'Profile Picture URL' column")
print()
print("  6. WhatsApp Accounts Information / User Profiles:")
print("     • account_name = 'WhatsApp Name' column")
print("     • account_id = 'Phone Number' column")
print("     • user_id = 'Phone Number' column (sama dengan account_id untuk WhatsApp)")
print("     • profile_picture_url = None atau dari kolom khusus jika ada")
print()

# Mapping untuk Cellebrite
print()
print("🟢 CELEBRITE:")
print()
print("  1. Social Media sheet:")
print("     • account_name = Extract dari 'Author' field (bagian setelah user_id)")
print("     • account_id = Extract dari 'Author' field (bagian pertama sebagai user_id)")
print("       atau dari 'Account' column")
print("     • user_id = Extract dari 'Author' field (bagian pertama)")
print("     • profile_picture_url = 'URL' column")
print()
print("  2. User Accounts sheet:")
print("     • account_name = 'Username' column")
print("     • account_id = Extract dari 'Entries' field:")
print("       - User ID-<value>")
print("       - User Id: <value>")
print("       - WhatsApp User Id: <value>")
print("       - Facebook Id: <value>")
print("       - Jika tidak ada, gunakan 'Username'")
print("     • user_id = Extract dari 'Entries' field (sama dengan account_id)")
print("     • profile_picture_url = Extract dari 'Entries' field:")
print("       - Profile Picture-<value>")
print("       - Profile Picture Url: <value>")
print("       - Pic Square: <value>")
print("       - profile_picture_url: <value>")
print()
print("  3. Contacts sheet:")
print("     • account_name = Extract dari URL/pattern:")
print("       - Instagram: instagram.com/(username)")
print("       - Facebook: Facebook Id: (id)")
print("       - WhatsApp: (+phone)@s.whatsapp.net")
print("       - Twitter: twitter.com/(username)")
print("       - TikTok: tiktok.com/@(username)")
print("       - Telegram: @(username)")
print("     • account_id = Sama dengan account_name untuk kebanyakan platform")
print("     • user_id = Sama dengan account_id")
print("     • profile_picture_url = None (tidak ada di Contacts sheet)")
print()
print("  4. Chats sheet:")
print("     • account_name = Extract dari 'Participants' field")
print("     • account_id = Extract dari 'Participants' field (bagian pertama)")
print("     • user_id = Extract dari 'Participants' field (bagian pertama)")
print("     • profile_picture_url = None")
print()

print()
print("=" * 100)
print("MASALAH YANG PERLU DIPERHATIKAN:")
print("=" * 100)
print()
print("1. ACCOUNT_NAME vs ACCOUNT_ID:")
print("   - account_name: Username yang bisa berubah (misal: @username, username)")
print("   - account_id: Identifier yang unik dan tidak berubah")
print("   - Untuk Instagram: account_id seharusnya User ID (numeric), bukan username")
print("   - Untuk WhatsApp: account_id = phone number")
print()
print("2. USER_ID:")
print("   - Biasanya sama dengan account_id untuk kebanyakan platform")
print("   - Untuk Instagram Axiom: User ID (numeric) berbeda dari username")
print("   - Untuk Cellebrite: User ID adalah bagian pertama dari Author field")
print()
print("3. PROFILE_PICTURE_URL:")
print("   - Tidak selalu tersedia di semua sheet")
print("   - Perlu extract dari berbagai field (Internet field untuk Oxygen, URL untuk Cellebrite)")
print("   - Pattern matching untuk URL image diperlukan")
print()
print("4. KONSISTENSI:")
print("   - Setiap tool memiliki format kolom yang berbeda")
print("   - Perlu mapping yang jelas untuk setiap sheet dari setiap tool")
print("   - Fallback logic diperlukan jika kolom tidak ditemukan")
print()

print()
print("=" * 100)
print("✅ REKOMENDASI PERBAIKAN:")
print("=" * 100)
print()
print("1. Buat mapping table yang jelas untuk setiap tool + sheet")
print("2. Pastikan account_id selalu menggunakan identifier yang unik (bukan username)")
print("3. Untuk Instagram: account_id = User ID (numeric), account_name = Username")
print("4. Untuk WhatsApp: account_id = Phone Number (normalized)")
print("5. Extract profile_picture_url dengan pattern matching yang lebih robust")
print("6. Tambahkan logging untuk tracking field yang tidak ditemukan")
print()

